/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AndheriBranchRouteImport } from './routes/andheri-branch'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as CareerGuidesRouteImport } from './routes/career-guides'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FranchiseRouteImport } from './routes/franchise'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GhatkoparBranchRouteImport } from './routes/ghatkopar-branch'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ScholarshipRouteImport } from './routes/scholarship'
import { Route as StudentSuccessRouteImport } from './routes/student-success'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as ThaneBranchRouteImport } from './routes/thane-branch'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CareerGuideAiDataScienceRouteImport } from './routes/career-guide.ai-data-science'
import { Route as CareerGuideAirportGroundStaffRouteImport } from './routes/career-guide.airport-ground-staff'
import { Route as CareerGuideCabinCrewRouteImport } from './routes/career-guide.cabin-crew'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesAiDataScienceWithGenerativeAiMachineLearningRouteImport } from './routes/courses.ai-data-science-with-generative-ai-machine-learning'
import { Route as CoursesAirHostessCabinCrewHospitalityManagementRouteImport } from './routes/courses.air-hostess-cabin-crew-hospitality-management'
import { Route as CoursesAirportGroundStaffHospitalityManagementRouteImport } from './routes/courses.airport-ground-staff-hospitality-management'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AndheriBranchRoute = AndheriBranchRouteImport.update({
  id: '/andheri-branch',
  path: '/andheri-branch',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerGuidesRoute = CareerGuidesRouteImport.update({
  id: '/career-guides',
  path: '/career-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FranchiseRoute = FranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GhatkoparBranchRoute = GhatkoparBranchRouteImport.update({
  id: '/ghatkopar-branch',
  path: '/ghatkopar-branch',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipRoute = ScholarshipRouteImport.update({
  id: '/scholarship',
  path: '/scholarship',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSuccessRoute = StudentSuccessRouteImport.update({
  id: '/student-success',
  path: '/student-success',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ThaneBranchRoute = ThaneBranchRouteImport.update({
  id: '/thane-branch',
  path: '/thane-branch',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerGuideAiDataScienceRoute =
  CareerGuideAiDataScienceRouteImport.update({
    id: '/career-guide/ai-data-science',
    path: '/career-guide/ai-data-science',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerGuideAirportGroundStaffRoute =
  CareerGuideAirportGroundStaffRouteImport.update({
    id: '/career-guide/airport-ground-staff',
    path: '/career-guide/airport-ground-staff',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerGuideCabinCrewRoute = CareerGuideCabinCrewRouteImport.update({
  id: '/career-guide/cabin-crew',
  path: '/career-guide/cabin-crew',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesAiDataScienceWithGenerativeAiMachineLearningRoute =
  CoursesAiDataScienceWithGenerativeAiMachineLearningRouteImport.update({
    id: '/courses/ai-data-science-with-generative-ai-machine-learning',
    path: '/courses/ai-data-science-with-generative-ai-machine-learning',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesAirHostessCabinCrewHospitalityManagementRoute =
  CoursesAirHostessCabinCrewHospitalityManagementRouteImport.update({
    id: '/courses/air-hostess-cabin-crew-hospitality-management',
    path: '/courses/air-hostess-cabin-crew-hospitality-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesAirportGroundStaffHospitalityManagementRoute =
  CoursesAirportGroundStaffHospitalityManagementRouteImport.update({
    id: '/courses/airport-ground-staff-hospitality-management',
    path: '/courses/airport-ground-staff-hospitality-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/andheri-branch': typeof AndheriBranchRoute
  '/branches': typeof BranchesRoute
  '/career-guides': typeof CareerGuidesRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/gallery': typeof GalleryRoute
  '/ghatkopar-branch': typeof GhatkoparBranchRoute
  '/placement': typeof PlacementRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/scholarship': typeof ScholarshipRoute
  '/student-success': typeof StudentSuccessRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thane-branch': typeof ThaneBranchRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/career-guide/ai-data-science': typeof CareerGuideAiDataScienceRoute
  '/career-guide/airport-ground-staff': typeof CareerGuideAirportGroundStaffRoute
  '/career-guide/cabin-crew': typeof CareerGuideCabinCrewRoute
  '/courses/ai-data-science-with-generative-ai-machine-learning': typeof CoursesAiDataScienceWithGenerativeAiMachineLearningRoute
  '/courses/air-hostess-cabin-crew-hospitality-management': typeof CoursesAirHostessCabinCrewHospitalityManagementRoute
  '/courses/airport-ground-staff-hospitality-management': typeof CoursesAirportGroundStaffHospitalityManagementRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/andheri-branch': typeof AndheriBranchRoute
  '/branches': typeof BranchesRoute
  '/career-guides': typeof CareerGuidesRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/gallery': typeof GalleryRoute
  '/ghatkopar-branch': typeof GhatkoparBranchRoute
  '/placement': typeof PlacementRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/scholarship': typeof ScholarshipRoute
  '/student-success': typeof StudentSuccessRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thane-branch': typeof ThaneBranchRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/career-guide/ai-data-science': typeof CareerGuideAiDataScienceRoute
  '/career-guide/airport-ground-staff': typeof CareerGuideAirportGroundStaffRoute
  '/career-guide/cabin-crew': typeof CareerGuideCabinCrewRoute
  '/courses/ai-data-science-with-generative-ai-machine-learning': typeof CoursesAiDataScienceWithGenerativeAiMachineLearningRoute
  '/courses/air-hostess-cabin-crew-hospitality-management': typeof CoursesAirHostessCabinCrewHospitalityManagementRoute
  '/courses/airport-ground-staff-hospitality-management': typeof CoursesAirportGroundStaffHospitalityManagementRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/locations': typeof LocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/andheri-branch': typeof AndheriBranchRoute
  '/branches': typeof BranchesRoute
  '/career-guides': typeof CareerGuidesRoute
  '/contact': typeof ContactRoute
  '/franchise': typeof FranchiseRoute
  '/gallery': typeof GalleryRoute
  '/ghatkopar-branch': typeof GhatkoparBranchRoute
  '/placement': typeof PlacementRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/scholarship': typeof ScholarshipRoute
  '/student-success': typeof StudentSuccessRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thane-branch': typeof ThaneBranchRoute
  '/thank-you': typeof ThankYouRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/career-guide/ai-data-science': typeof CareerGuideAiDataScienceRoute
  '/career-guide/airport-ground-staff': typeof CareerGuideAirportGroundStaffRoute
  '/career-guide/cabin-crew': typeof CareerGuideCabinCrewRoute
  '/courses/ai-data-science-with-generative-ai-machine-learning': typeof CoursesAiDataScienceWithGenerativeAiMachineLearningRoute
  '/courses/air-hostess-cabin-crew-hospitality-management': typeof CoursesAirHostessCabinCrewHospitalityManagementRoute
  '/courses/airport-ground-staff-hospitality-management': typeof CoursesAirportGroundStaffHospitalityManagementRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/andheri-branch'
    | '/branches'
    | '/career-guides'
    | '/contact'
    | '/franchise'
    | '/gallery'
    | '/ghatkopar-branch'
    | '/placement'
    | '/privacy-policy'
    | '/refund-policy'
    | '/scholarship'
    | '/student-success'
    | '/terms-and-conditions'
    | '/thane-branch'
    | '/thank-you'
    | '/blog/$slug'
    | '/career-guide/ai-data-science'
    | '/career-guide/airport-ground-staff'
    | '/career-guide/cabin-crew'
    | '/courses/ai-data-science-with-generative-ai-machine-learning'
    | '/courses/air-hostess-cabin-crew-hospitality-management'
    | '/courses/airport-ground-staff-hospitality-management'
    | '/locations/$slug'
    | '/blog/'
    | '/courses/'
    | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/andheri-branch'
    | '/branches'
    | '/career-guides'
    | '/contact'
    | '/franchise'
    | '/gallery'
    | '/ghatkopar-branch'
    | '/placement'
    | '/privacy-policy'
    | '/refund-policy'
    | '/scholarship'
    | '/student-success'
    | '/terms-and-conditions'
    | '/thane-branch'
    | '/thank-you'
    | '/blog/$slug'
    | '/career-guide/ai-data-science'
    | '/career-guide/airport-ground-staff'
    | '/career-guide/cabin-crew'
    | '/courses/ai-data-science-with-generative-ai-machine-learning'
    | '/courses/air-hostess-cabin-crew-hospitality-management'
    | '/courses/airport-ground-staff-hospitality-management'
    | '/locations/$slug'
    | '/blog'
    | '/courses'
    | '/locations'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about-us'
    | '/andheri-branch'
    | '/branches'
    | '/career-guides'
    | '/contact'
    | '/franchise'
    | '/gallery'
    | '/ghatkopar-branch'
    | '/placement'
    | '/privacy-policy'
    | '/refund-policy'
    | '/scholarship'
    | '/student-success'
    | '/terms-and-conditions'
    | '/thane-branch'
    | '/thank-you'
    | '/blog/$slug'
    | '/career-guide/ai-data-science'
    | '/career-guide/airport-ground-staff'
    | '/career-guide/cabin-crew'
    | '/courses/ai-data-science-with-generative-ai-machine-learning'
    | '/courses/air-hostess-cabin-crew-hospitality-management'
    | '/courses/airport-ground-staff-hospitality-management'
    | '/locations/$slug'
    | '/blog/'
    | '/courses/'
    | '/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutUsRoute: typeof AboutUsRoute
  AndheriBranchRoute: typeof AndheriBranchRoute
  BranchesRoute: typeof BranchesRoute
  CareerGuidesRoute: typeof CareerGuidesRoute
  ContactRoute: typeof ContactRoute
  FranchiseRoute: typeof FranchiseRoute
  GalleryRoute: typeof GalleryRoute
  GhatkoparBranchRoute: typeof GhatkoparBranchRoute
  PlacementRoute: typeof PlacementRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ScholarshipRoute: typeof ScholarshipRoute
  StudentSuccessRoute: typeof StudentSuccessRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ThaneBranchRoute: typeof ThaneBranchRoute
  ThankYouRoute: typeof ThankYouRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CareerGuideAiDataScienceRoute: typeof CareerGuideAiDataScienceRoute
  CareerGuideAirportGroundStaffRoute: typeof CareerGuideAirportGroundStaffRoute
  CareerGuideCabinCrewRoute: typeof CareerGuideCabinCrewRoute
  CoursesAiDataScienceWithGenerativeAiMachineLearningRoute: typeof CoursesAiDataScienceWithGenerativeAiMachineLearningRoute
  CoursesAirHostessCabinCrewHospitalityManagementRoute: typeof CoursesAirHostessCabinCrewHospitalityManagementRoute
  CoursesAirportGroundStaffHospitalityManagementRoute: typeof CoursesAirportGroundStaffHospitalityManagementRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/andheri-branch': {
      id: '/andheri-branch'
      path: '/andheri-branch'
      fullPath: '/andheri-branch'
      preLoaderRoute: typeof AndheriBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-guides': {
      id: '/career-guides'
      path: '/career-guides'
      fullPath: '/career-guides'
      preLoaderRoute: typeof CareerGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franchise': {
      id: '/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof FranchiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghatkopar-branch': {
      id: '/ghatkopar-branch'
      path: '/ghatkopar-branch'
      fullPath: '/ghatkopar-branch'
      preLoaderRoute: typeof GhatkoparBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship': {
      id: '/scholarship'
      path: '/scholarship'
      fullPath: '/scholarship'
      preLoaderRoute: typeof ScholarshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-success': {
      id: '/student-success'
      path: '/student-success'
      fullPath: '/student-success'
      preLoaderRoute: typeof StudentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thane-branch': {
      id: '/thane-branch'
      path: '/thane-branch'
      fullPath: '/thane-branch'
      preLoaderRoute: typeof ThaneBranchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-guide/ai-data-science': {
      id: '/career-guide/ai-data-science'
      path: '/career-guide/ai-data-science'
      fullPath: '/career-guide/ai-data-science'
      preLoaderRoute: typeof CareerGuideAiDataScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-guide/airport-ground-staff': {
      id: '/career-guide/airport-ground-staff'
      path: '/career-guide/airport-ground-staff'
      fullPath: '/career-guide/airport-ground-staff'
      preLoaderRoute: typeof CareerGuideAirportGroundStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-guide/cabin-crew': {
      id: '/career-guide/cabin-crew'
      path: '/career-guide/cabin-crew'
      fullPath: '/career-guide/cabin-crew'
      preLoaderRoute: typeof CareerGuideCabinCrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/ai-data-science-with-generative-ai-machine-learning': {
      id: '/courses/ai-data-science-with-generative-ai-machine-learning'
      path: '/courses/ai-data-science-with-generative-ai-machine-learning'
      fullPath: '/courses/ai-data-science-with-generative-ai-machine-learning'
      preLoaderRoute: typeof CoursesAiDataScienceWithGenerativeAiMachineLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/air-hostess-cabin-crew-hospitality-management': {
      id: '/courses/air-hostess-cabin-crew-hospitality-management'
      path: '/courses/air-hostess-cabin-crew-hospitality-management'
      fullPath: '/courses/air-hostess-cabin-crew-hospitality-management'
      preLoaderRoute: typeof CoursesAirHostessCabinCrewHospitalityManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/airport-ground-staff-hospitality-management': {
      id: '/courses/airport-ground-staff-hospitality-management'
      path: '/courses/airport-ground-staff-hospitality-management'
      fullPath: '/courses/airport-ground-staff-hospitality-management'
      preLoaderRoute: typeof CoursesAirportGroundStaffHospitalityManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutUsRoute: AboutUsRoute,
  AndheriBranchRoute: AndheriBranchRoute,
  BranchesRoute: BranchesRoute,
  CareerGuidesRoute: CareerGuidesRoute,
  ContactRoute: ContactRoute,
  FranchiseRoute: FranchiseRoute,
  GalleryRoute: GalleryRoute,
  GhatkoparBranchRoute: GhatkoparBranchRoute,
  PlacementRoute: PlacementRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ScholarshipRoute: ScholarshipRoute,
  StudentSuccessRoute: StudentSuccessRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ThaneBranchRoute: ThaneBranchRoute,
  ThankYouRoute: ThankYouRoute,
  BlogSlugRoute: BlogSlugRoute,
  CareerGuideAiDataScienceRoute: CareerGuideAiDataScienceRoute,
  CareerGuideAirportGroundStaffRoute: CareerGuideAirportGroundStaffRoute,
  CareerGuideCabinCrewRoute: CareerGuideCabinCrewRoute,
  CoursesAiDataScienceWithGenerativeAiMachineLearningRoute:
    CoursesAiDataScienceWithGenerativeAiMachineLearningRoute,
  CoursesAirHostessCabinCrewHospitalityManagementRoute:
    CoursesAirHostessCabinCrewHospitalityManagementRoute,
  CoursesAirportGroundStaffHospitalityManagementRoute:
    CoursesAirportGroundStaffHospitalityManagementRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
